services :
  
  mysql:

    image : mysql:8.4

    environment :
      MYSQL_ROOT_PASSWORD : Root123
      MYSQL_DATABASE : expense_tracker
      MYSQL_USER : expense
      MYSQL_PASSWORD : tracker

    ports :
      - "3306:3306"

    volumes :
      - expense_mysql_data:/var/lib/mysql


volumes :
  expense_mysql_data:
