spring:
  application:
    name: expense-tracker

  datasource:
    url : jdbc:mysql://localhost:3306/expense_tracker
    username : expense
    password : tracker 

  jpa:
    hibernate:
      ddl-auto : validate