spring:
  application:
    name: expense-tracker

  datasource:
    url : jdbc:mysql://localhost:3306/expense_tracker
    username : expense
    password : tracker 

  jpa:
    hibernate:
      ddl-auto : validate

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/expense-tracker

app:
  security:
    jwt-secret: ${JWT_SECRET}

    

